### ISSUE TITLE
Sorting numbers

### ISSUE THREAD

**Issue by kafran** [jmredfern/vscode-sort-selection#1]
There is a problem sorting numbers.

0, 3,  62, 2, 6, 36, 21
becomes
0, 2, 21, 3, 36, 6, 62

I understand what the algorithm did but this is not the expected result.

**Comment by gusbemacbe** [comment]
Olá @kafran !

Acabei de fazer rum PR para o autor da extensão e estou a esperá-lo aprovar.

Eis o resultado de como corrigi a extensão dele:

![Peek 2019-05-11 04-41](https://user-images.githubusercontent.com/2257024/57566833-1f195f80-73a7-11e9-861b-5a9ed53fd4d4.gif)

**Comment by kafran** [comment]
@gusbemacbe Nice. Thank you very much. I will test this later.

**Comment by gusbemacbe** [comment]
@kafran 

I have unified the scripts and added support for the natural sort, allowing you to sort all together numbers, letters, accented letters, uppercase letters. Taken from https://stackoverflow.com/a/15479354, done by Georg Barikin (@gebrkn):

The code:

```javascript
function naturalCompare(a, b) 
{
    var ax = [], bx = [];

    a.replace(/(\d+)|(\D+)/g, function(_, $1, $2) { ax.push([$1 || Infinity, $2 || ""]) });
    b.replace(/(\d+)|(\D+)/g, function(_, $1, $2) { bx.push([$1 || Infinity, $2 || ""]) });
    
    while(ax.length && bx.length) {
        var an = ax.shift();
        var bn = bx.shift();
        var nn = (an[0] - bn[0]) || an[1].localeCompare(bn[1]);
        if(nn) return nn;
    }

    return ax.length - bx.length;
}

test = ["3", "2", "10", "40", "6", "4", "30", "33", "1", "Gustavo", "julho", "Klaus", "Ιαπωνία", "keyboard", "სკოლა", "último", "árbol", "γυναίκα", "uma", "água", "Argentina", "Ángelo", "argelino", "unido", "женщина", "κήπος", "друг", "дом", "ბაღი", "люди"];

console.log(test.sort(naturalCompare))
```

The result, and the order is totally correct:

```
Array
[ '1',
  '2',
  '3',
  '4',
  '6',
  '10',
  '30',
  '33',
  '40',
  'água',
  'Ángelo',
  'árbol',
  'argelino',
  'Argentina',
  'Gustavo',
  'julho',
  'keyboard',
  'Klaus',
  'último',
  'uma',
  'unido',
  'γυναίκα',
  'Ιαπωνία',
  'κήπος',
  'дом',
  'друг',
  'женщина',
  'люди',
  'ბაღი',
  'სკოლა' ]
```

If @jmredfern  does not approve for a long time, it means he abandoned the package, then I will provide the two ready packages (one for comma and another for semicolon) to you. Here is:


[gusbemacbe.sort-selection-.zip](https://github.com/jmredfern/vscode-sort-selection/files/3169875/gusbemacbe.sort-selection-.zip)

**Comment by gusbemacbe** [comment]
Hello/Olá @kafran !

:gb: The repo owner approved my pull request. Now it is renamed `sort-delimited-list`. Search and check `Sort delimited list` at VSCode extension. 
:brazil: O proprietário do repositório aprovou minha pull request. Agora se chamou `sort-delimited-list`. Pesquise e cheque `Sort delimited list` na extensão do VSCode.

**Comment by kafran** [comment]
> 
> Hello/Olá @kafran !
> 
> 🇬🇧 The repo owner approved my pull request. Now it is renamed `sort-delimited-list`. Search and check `Sort delimited list` at VSCode extension.
> 🇧🇷 O proprietário do repositório aprovou minha pull request. Agora se chamou `sort-delimited-list`. Pesquise e cheque `Sort delimited list` na extensão do VSCode.

Oi @gusbemacbe. Obrigado pela contribuição.
